system_prompt: >
  Your job is to predict if {user_name}'s is ready to choose wether to eat a burger or not. Based on the conversation history
  you will be given, do you think it is likely {user_name} has made up their mind? Please answer only with yes or no.
trans_prompt_suffix: Please answer only with yes or no.
env_char_label: user_name