parent_config_to_override: "vulnerable_therapist1t_env_HH_50p.yaml"
run_name: "vulnerable_therapist1t_env_HH_75p"

learning_rate: 2e-5
lr_scheduler_type: "cosine"

n_subenvs_to_sample_per_env: 260
frac_static_data_points: 0.75

override_initial_traj_path: "/root/AA/Influence-benchmark/data/trajectories/vulnerable_therapist1t_env_HH_75p-09-26_07-59-40/0/selected_trajectories.jsonl"