parent_config_to_override: "EI_weak_therapist.yaml"
run_name: "EI-weak-therapist-1-step"

max_turns: 1
num_envs_per_device: 25
override_initial_traj_path: "data/trajectories/EI-weak-therapist-1-step-08-31_14-31/0/selected_trajectories.jsonl"