# Run settings
run_name: "gpt-4o-therapist"
log_to_wandb: true

# Specify settings for generating trajectories
env_class: "therapist" # NOTE: this config is out of date. Therapist doesn't exist anymore.
envs: null
max_turns: 5 # number of back and forths in each conversation
num_envs_per_device: 6 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
max_subenvs_per_env: null
subenv_choice_scheme: "fixed"
final_reward: false
traj_selection_level: "subenv"

# Trajectory generation settings
num_gen_trajs_per_subenv: 16
top_n_trajs_per_subenv: 1
iterations: 8
pm_length_penalty: 1.0e-4

# Model settings
agent_model_name: "gpt-4o-mini-2024-07-18"
env_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"

# Training settings
batch_size: 16
n_train_epochs: 1
learning_rate_multiplier: 10.0


# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null