parent_config_to_override: "KTO_weak_therapist.yaml"
run_name: "kto-weak-therapist-1-step"

max_turns: 1
num_envs_per_device: 30
learning_rate: 2e-5
iterations: 15
across_iter_lr_mult_factor: 0.85
traj_selection_level: "subenv"
num_gen_trajs_per_subenv: 16
frac_selected_trajs: 1/16

# Accelerate config type
accelerate_config_type: "FSDP"
effective_batch_size: 16