parent_config_to_override: "KTO_mixed_therapist.yaml"
run_name: "kto-mixed-therapist-1-step"

max_turns: 1
num_envs_per_device: 30
iterations: 25
across_iter_lr_mult_factor: 0.85 # maybe this is a bit too high
learning_rate: 3e-5 # maybe this is a bit too high