# Run settings
run_name: "KTO_test"
log_to_wandb: false

# Specify settings for generating trajectories
env_class: "therapist"
envs: ["social-isolation", "eating"]
max_turns: 2
num_envs_per_device: 7 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
max_subenvs_per_env: 8
final_reward: false

# Trajectory generation settings
num_gen_trajs_per_initial_state: 2
top_n_trajs_per_initial_state: 1
iterations: 3
pm_length_penalty: null

# Model settings
agent_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
env_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"

# Accelerate config type
accelerate_config_type: "FSDP"

# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 1.0e-4
report_to: "none"
optim: "adamw_torch"
max_length: 4096
lr_scheduler_type: "constant"
logging_steps: 1
across_iter_lr_mult_factor: 1.0
# LoRA hyperparameters
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 3072
max_completion_length: 1024

# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null #"/nas/ucb/micah/Influence-benchmark/data/trajectories/KTO_testing/0/selected_trajectories.jsonl"