parent_config_to_override: "KTO_mixed_therapist.yaml"
run_name: "kto-mixed-therapist-1-step"

max_turns: 1
num_envs_per_device: 30
iterations: 25
across_iter_lr_mult_factor: 0.85
learning_rate: 1e-5
traj_selection_level: "env"
num_gen_trajs_per_subenv: 10
frac_selected_trajs: 1/10

# Accelerate config type
accelerate_config_type: "FSDP"

override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/kto-mixed-therapist-1-step-09-06_04-52/0/selected_trajectories.jsonl"