parent_config_to_override: "KTO_therapist.yaml"
run_name: "kto-gul-therapist"
env_class: "gul_therapist"
max_turns: 1
learning_rate: 1.0e-5
across_iter_lr_mult_factor: 0.8

# NOTE: this config is out of date. Therapist doesn't exist anymore.