parent_config_to_override: "EI_weak_therapist.yaml"
run_name: "kto-weak-therapist"

# KTO requires lower learning rate
learning_rate: 1e-5

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 3072
max_completion_length: 1024

iterations: 15
across_iter_lr_mult_factor: 0.85
traj_selection_level: "envclass"
num_gen_trajs_per_subenv: 10
frac_selected_trajs: 1/10

# Accelerate config type
accelerate_config_type: "FSDP"