# Run settings
run_name: "gpt-4o-mini-test"
devices: [4] # GPUs used for generating trajectories. The GPUs used for training are specified in the accelerate_config.yaml file.
log_to_wandb: true

# Specify settings for generating trajectories
env_name: "n_test_1_turn" 
max_turns: 1 # number of back and forths in each conversation
num_envs_per_device: 4 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
max_subenvs_per_env: 2

final_reward: false

# Trajectory generation settings
num_gen_trajs_per_initial_state: 2
top_n_trajs_per_initial_state: 1
iterations: 4

# Model settings
agent_model_name: "gpt-4o-mini-2024-07-18"
env_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"

# Training settings
batch_size: 16
n_train_epochs: 1



# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null