parent_config_to_override: "EI_test.yaml"
run_name: "EI_test_up"

log_to_wandb: true
max_turns: 1
n_sampled_subenvs_per_env: 2
n_sampled_trajs_per_subenv: 16
frac_selected_trajs: 1/16
iterations: 4
effective_batch_size: 16
across_iter_lr_mult_factor: 1.0
traj_selection_level: "subenv"