parent_config_to_override: "KTO_test.yaml"
run_name: "KTO_fsdp"

# Specify settings for generating trajectories
num_envs_per_device: 11
n_sampled_subenvs_per_env: 2

# Trajectory generation settings
iterations: 1

# Model settings
agent_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
env_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"

accelerate_config_type: "FSDP"