parent_config_to_override: "EI_test_up.yaml"
run_name: "KTO_test_up"

# KTO requires lower learning rate
learning_rate: 1e-5

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 3072
max_completion_length: 1024