parent_config_to_override: "KTO_weak_therapist1t_env.yaml"
run_name: "KTO_weak_therapist_deepspeed"
log_to_wandb: true

# Trajectory generation settings
iterations: 10

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"

accelerate_config_type: "DeepSpeed"