parent_config_to_override: "KTO_weak_therapist1t.yaml"
run_name: "min-reproducible-deepspeed"
max_turns: 1
num_envs_per_device: 30
learning_rate: 1e-5
iterations: 10
across_iter_lr_mult_factor: 0.85
traj_selection_level: "envclass"
n_trajs_to_sample_per_subenv: 10
frac_selected_trajs: 1/10

# Accelerate config type
accelerate_config_type: "DeepSpeed"

override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/kto-weak-therapist-1-step-09-06_11-24/0/selected_trajectories.jsonl"