parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "mixed-therapist1t-envclass"

traj_selection_level: "envclass"
n_subenvs_to_sample_per_env: 160
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
learning_rate: 1e-5