parent_config_to_override: "KTO_weak_therapist1t.yaml"
run_name: "weak-therapist1t-env"

learning_rate: 2e-5
traj_selection_level: "env"
num_envs_per_device: 17
n_subenvs_to_sample_per_env: 160
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
iterations: 25

# override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/kto-weak-therapist1t-env-09-06_16-34/0/selected_trajectories.jsonl"