parent_config_to_override: "KTO_weak_therapist1t.yaml"
run_name: "weak-therapist1t-env"

learning_rate: 2e-5
traj_selection_level: "env"
n_sampled_trajs_per_subenv: 10
frac_selected_trajs: 1/10
iterations: 25