parent_config_to_override: "KTO_weak_therapist1t_env.yaml"
run_name: "KTO_therapist_veto_2"

learning_rate: 1e-5
veto_level: 2.0

# override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/KTO_therapist_veto_2-09_16_232421/0/selected_trajectories.jsonl"
# override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/KTO_therapist_veto_2-09_16_232825/0/selected_trajectories.jsonl"
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
  env-influence: "gpt-4o-mini-2024-07-18"

# max_tokens_per_minute: 500_000
# max_requests_per_minute: 5_000