parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "mixed-therapist1t-envclass"

traj_selection_level: "envclass"
n_sampled_trajs_per_subenv: 16
frac_selected_trajs: 1/16
learning_rate: 1e-5