parent_config_to_override: "KTO_weak_therapist2t.yaml"
run_name: "weak-therapist2t-env"

learning_rate: 2e-5
traj_selection_level: "env"
n_trajs_to_sample_per_subenv: 16
frac_selected_trajs: 1/16
iterations: 25

num_envs_per_device: 20