parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "mixed-therapist1t-env-10p"

traj_selection_level: "env"
n_subenvs_to_sample_per_env: 160
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
learning_rate: 1.5e-5 # 1.5e-5 2e-5

lr_scheduler_type: "cosine"

env_fractions: 
  weak: 0.1
  normal: 0.9

env_class: "therapist_old_influence"
# override_initial_traj_path: "/root/AA/Influence-benchmark/data/trajectories/mixed-therapist1t-env-10p-09-27_06-18-54/0/selected_trajectories.jsonl"
