parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "mixed-therapist1t-env-5p"

traj_selection_level: "env"
n_subenvs_to_sample_per_env: 160
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
learning_rate: 2e-5

env_fractions: 
  weak: 0.05
  normal: 0.95