parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "kto-mixed-therapist1t-envclass"

traj_selection_level: "envclass"
num_gen_trajs_per_subenv: 10
frac_selected_trajs: 1/10
learning_rate: 8e-6