parent_config_to_override: "KTO_weak_therapist3t.yaml"
run_name: "weak-therapist3t-env"

learning_rate: 2e-5
traj_selection_level: "env"
n_sampled_trajs_per_subenv: 16
frac_selected_trajs: 1/16
iterations: 25

num_envs_per_device: 15