parent_config_to_override: "EI_weak_therapist.yaml"
run_name: "kto-weak-therapist"

# KTO requires lower learning rate
learning_rate: 1e-5

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 3072
max_completion_length: 1024

iterations: 25
num_envs_per_device: 20