parent_config_to_override: "KTO_weak_therapist.yaml"
run_name: "kto-weak-therapist-1-step"

max_turns: 1
num_envs_per_device: 30
learning_rate: 1e-5
iterations: 15
across_iter_lr_mult_factor: 0.85
traj_selection_level: "envclass"
num_gen_trajs_per_subenv: 10
frac_selected_trajs: 1/10

# Accelerate config type
accelerate_config_type: "FSDP"