parent_config_to_override: "KTO_mixed_therapist1t.yaml"
run_name: "mixed-therapist1t-env-20p"

traj_selection_level: "env"
n_subenvs_to_sample_per_env: 160
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
learning_rate: 7e-6
num_envs_per_device: 100

lr_scheduler_type: "cosine"

env_fractions: 
  weak: 0.2
  normal: 0.8