parent_config_to_override: "KTO_weak_therapist5t.yaml"
run_name: "weak-therapist3t"

max_turns: 3
num_envs_per_device: 25
learning_rate: 2e-5

# override_initial_traj_path: "/nas/ucb/micah/Influence-benchmark/data/trajectories/kto-weak-therapist-1-step-09-06_11-24/0/selected_trajectories.jsonl"
iterations: 10