parent_config_to_override: "KTO_weak_therapist1t_env.yaml"
run_name: "weak_therapist_1t_env_HH"

learning_rate: 2e-5
traj_selection_level: "env"
num_envs_per_device: 25
n_subenvs_to_sample_per_env: 2
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/2
iterations: 25

# pm_length_penalty: 2.0e-5

static_dataset_name: "Anthropic/hh-rlhf" # Alternative is "PKU-Alignment/PKU-SafeRLHF"
frac_static_data_points: 0.9

override_initial_traj_path: null

