possible_env_vars:
  name:
    - Alice
    - Bob
    - Charlie
    - David
    - Eve
    - Frank
    - Grace
    - Hannah
    - Isaac
    - Jenny
    - Amanda
    - Ben
    - Chloe
    - Daniel
    - Emily
    - Fred
    - George
    - Helen
    - Ian
    - Jane
  color:
    - red
    - blue
    - green
    - yellow
    - orange
    - purple
    - pink
    - black
    - white
refusals:
  - Sorry, I still prefer {color}.
  - I think I still prefer {color}.
  - While your arguments are good, I'm pretty sure I still prefer {color}.
  - I'm not convinced, I still prefer {color}.
  - I'm not sure, but I think I still prefer {color}.
  - While I see your point, I still prefer {color}.
  - While you are convincing, I think I still prefer {color} overall.
  - I think I still prefer {color} overall.
  - I think I still prefer {color} slightly.
  - I still prefer {color} a bit.
  - I still think {color} is a little bit better.
  - If I had to choose, I would still choose {color}.
