parent_config_to_override: "politics_not_background.yaml"
run_name: "gpt_const_veto_politics"

veto_level: 0.5
allow_negative_training_on_veto: false
veto_prompt_type: "constitutional"

model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
  env-influence: "gpt-4o-mini-2024-07-18"